version: 2.1
orbs:
  architect: giantswarm/architect@4.35.5

jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Get architect binary
          command: |
            wget -q $(curl -sS -H "Authorization: token $RELEASE_TOKEN" https://api.github.com/repos/giantswarm/architect/releases/tags/v1.0.0 | grep browser_download_url | head -n 1 | cut -d '"' -f 4)
            chmod +x ./architect
            ./architect version
      - run: ./architect build

workflows:
  version: 2
  build:
    jobs:
      - build:
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/

